spring:
  datasource:
    name: portier_digital
    url: jdbc:mysql://localhost:3306/slj_kinocms1
    username: slj_kinocms
    password: 4h8bLzSDig
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: false
  servlet:
    multipart:
      max-file-size: 50MB
      max-request-size: 50MB

server:
  port: 8084
  servlet:
    context-path: "/PortierDigital-R.Pravnyk"

upload:
  path: "/home/slj/projects/PortierDigital-R.Pravnyk/uploads"