name: Java CI pipeline
on:
  push:
    branches: [ "dev" ]
jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Git Repo
        uses: actions/checkout@v3
#
#      - name: Set up JDK 17
#        uses: actions/setup-java@v3
#        with:
#          java-version: '17'
#          distribution: 'temurin'
#          cache: 'maven'
#
#      - name: Build with Maven
#        run: mvn clean package -D skipTests=true war:war
#
#      - name: Update application.yaml
#        run: |
#
#
#      - name: Upload Artifact
#        uses: actions/upload-artifact@v4
#        with:
#          name: petclinic-war
#          path: "/petclinic.war"
