name: Java CI pipeline
on:
  push:
    branches: [ "dev" ]
jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Git Repo
        uses: actions/checkout@v4

      - name: Set up JDK 17
        uses: actions/setup-java@v4.2.1
        with:
          java-version: '17'
          distribution: 'corretto'
          cache: 'maven'

      - name: Build app
        run: |
         mvn clean
         mvn package -DskipTests=true
        env:
          DB_HOST: ${{ secrets.DB_HOST }}
          DB_LOGIN: ${{ secrets.DB_LOGIN }}
          DB_PASSWORD: ${{ secrets.DB_PASSWORD }}

      - name: Tomcat Deploy
        env:
          CICD_MANAGER_URL: https://slj.demodev.cc/manager/text/deploy?path=/PortierDigital-R.Pravnyk&update=true
          CICD_USERNAME: ${{ secrets.CICD_LOGIN }}
          CICD_PASSWORD: ${{ secrets.CICD_PASSWORD }}
        run: |
            curl -v -u $CICD_USERNAME:$CICD_PASSWORD -T target/*.war "$CICD_MANAGER_URL"
            curl -v -u $CICD_USERNAME:$CICD_PASSWORD "${CICD_MANAGER_URL/%\/deploy/\/reload}"