name: Java CI pipeline
on:
  push:
    branches: [ "dev" ]
jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Git Repo
        uses: actions/checkout@v3

      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'
          cache: 'maven'

      - name: Build app
        run:
         mvn clean
         mvn package -DskipTests=true

        env:
          ${{ secrets.DB_HOST }}
          ${{ secrets.DB_LOGIN }}
          ${{ secrets.DB_PASSWORD }}

