name: Build & Deploy
on:
  push:
    branches:
      - dev
jobs:
  build-deploy:
    name: Build and Deploy spring boot application
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Setup JDK 17
        uses: actions/setup-java@v4.2.1
        with:
          distribution: 'corretto'
          java-version: 17

      - name: Build application
        run: |
          mvn clean
          
          sed -i "s|\${DB_URL}|${{ secrets.DB_URL }}|g" src/main/resources/application.yaml
          sed -i "s|\${DB_USERNAME}|${{ secrets.DB_USERNAME }}|g" src/main/resources/application.yaml
          sed -i "s|\${DB_PASSWORD}|${{ secrets.DB_PASSWORD }}|g" src/main/resources/application.yaml
          
          mvn package -DskipTests=true

      - name: Tomcat Deploy
        env:
          TOMCAT_MANAGER_URL: https://slj.demodev.cc/manager/text/deploy?path=/PortierDigital-R.Pravnyk&update=true
          TOMCAT_USERNAME: ${{ secrets.TOMCAT_USERNAME }}
          TOMCAT_PASSWORD: ${{ secrets.TOMCAT_PASSWORD }}
        run: |
          curl -v -u $TOMCAT_USERNAME:$TOMCAT_PASSWORD -T target/*.war "$TOMCAT_MANAGER_URL"
          curl -v -u $TOMCAT_USERNAME:$TOMCAT_PASSWORD "${TOMCAT_MANAGER_URL/%\/deploy/\/reload}"