name: Java CI pipeline
on:
  push:
    branches: [ "dev" ]
jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Git Repo
        uses: actions/checkout@v3

      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'
          cache: 'maven'

      - name: Build app
        run: |
         mvn clean
         mvn package -DskipTests=true
        env:
          DB_HOST: ${{ secrets.DB_HOST }}
          DB_LOGIN: ${{ secrets.DB_LOGIN }}
          DB_PASSWORD: ${{ secrets.DB_PASSWORD }}

      - name: Copy file
        uses: garygrossgarten/github-action-scp@release
        with:
          local: target/PortierDigital-R.Pravnyk.war
          remote: home/slj/webapps/slj.demodev.cc/PortierDigital-R.Pravnyk.war
          host: ${{ secrets.SSH_URL }}
          username: ${{ secrets.SSH_LOGIN }}
          password: ${{ secrets.SSH_PASSWORD }}