name: Java CI pipeline
on:
  push:
    branches: [ "dev" ]
jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Git Repo
        uses: actions/checkout@v3

      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'
          cache: 'maven'

      - name: Build app
        run:
          mvn clean
          
          sed -i "s|\${DB_HOST}|${{ secrets.DB_HOST }}|g" src/main/resources/application.yaml
          sed -i "s|\${DB_LOGIN}|${{ secrets.DB_LOGIN }}|g" src/main/resources/application.yaml
          sed -i "s|\${DB_PASSWORD}|${{ secrets.DB_PASSWORD }}|g" src/main/resources/application.yaml
        
          mvn package -DskipTests=true

#      - name: Upload Artifact
#        uses: actions/upload-artifact@v4
#        with:
#          name: petclinic-war
#          path: "/petclinic.war"
